-- Instructions to execute this file (PostgreSQL + psql on Linux)
--
-- Step 1: Create a database named college_db:
--      createdb -U postgres -h localhost -W college_db
--
-- Step 2: Execute this script on the college_db database:
--      psql -U postgres -h localhost -W -d college_db -f /<path-to-file>/task_01.sql

CREATE TABLE departments (
    department_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dept_name VARCHAR(100) NOT NULL,
    hod_name VARCHAR(100),
    budget DECIMAL(12,2) CHECK (budget >= 0)
);

CREATE TABLE students (
    student_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(50) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    date_of_birth DATE,
    department_id INT,
    enrollment_year INT,

    CONSTRAINT fk_department_students
        FOREIGN KEY (department_id)
        REFERENCES departments(department_id)
        ON DELETE RESTRICT
);

CREATE TABLE courses (
    course_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR(150) NOT NULL,
    course_code VARCHAR(20) UNIQUE,
    credits INT CHECK (credits >= 0),
    department_id INT,

    CONSTRAINT fk_department_courses
        FOREIGN KEY (department_id)
        REFERENCES departments(department_id)
        ON DELETE RESTRICT
);

CREATE TABLE enrollments (
    enrollment_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INT,
    course_id INT,
    enrollment_date DATE,
    grade CHAR(2),

    CONSTRAINT chk_grade
        CHECK (
            grade IS NULL OR
            grade IN ('A', 'B', 'C', 'D', 'F')
        ),
    
    CONSTRAINT uq_student_course
        UNIQUE (student_id, course_id),

    CONSTRAINT fk_students_enrollments
        FOREIGN KEY (student_id)
        REFERENCES students(student_id)
        ON DELETE RESTRICT,

    CONSTRAINT fk_courses_enrollments
        FOREIGN KEY (course_id)
        REFERENCES courses(course_id)
        ON DELETE RESTRICT
);

CREATE TABLE professors (
    professor_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    prof_name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE,
    department_id INT,
    salary DECIMAL(10,2) CHECK (salary >= 0),

    CONSTRAINT fk_department_professors
        FOREIGN KEY (department_id)
        REFERENCES departments(department_id)
        ON DELETE RESTRICT
);